trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'flask-app' # Your Docker Hub connection service name
    repository: 'davidmdansell/order-management-app' # Replace with your Docker Hub username and image name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile' # Path to your Dockerfile
    tags: 'v1.0'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azure-rm-service' # AKS service connection name
    azureResourceGroup: 'networking-rg' # AKS resource group
    kubernetesCluster: 'terraform-aks-cluster' # AKS cluster name
    command: 'apply'
    secretType: 'None'
    useConfigurationFile: true
    configurationType: 'FilePath'
    filePath: '/Users/davidansell/devops-pipeline-project/Web-App-DevOps-Project/my-terraform-project/application-manifest.yaml' # Path to your deployment manifest in the repository