trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'flask-app' # Your Docker Hub connection service name
    repository: 'davidmdansell/order-management-app' # Replace with your Docker Hub username and image name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile' # Path to your Dockerfile
    tags: 'v1.0'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Dario Stefano DevOps(4)(5668e4c9-8365-4a1a-80b3-233adb861c80)'
    azureResourceGroup: 'networking-rg'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'