apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # Port for internal communication within the cluster
    targetPort: 5000  # Port exposed by your container
  type: ClusterIP  # Internal service

